
from celery_app import tasks
from conf import settings

tasks.convertData(settings.TARGET_READ_TODAY_PATH,settings.GRID_DAILY_SOURCE_FILENAME,settings.GRID_DAILY_SOURCE_EXT,settings.TARGET_SAVE_MID_PATH,settings.GRID_DAILY_MID_FILENAME,settings.GRID_DAILY_MID_EXT)