# Generated by Django 2.0.4 on 2018-07-30 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StormTideInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('tdate', models.DateField(default=datetime.datetime.now)),
                ('surge', models.FloatField(default=-999.0)),
                ('tide', models.FloatField(default=-999.0)),
                ('code', models.CharField(default='ERROR', max_length=6)),
            ],
            options={
                'verbose_name': '每日风暴潮及增水详细数据',
                'verbose_name_plural': '每日风暴潮及增水详细数据',
            },
        ),
    ]
