# Generated by Django 2.0.4 on 2018-07-30 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StormTide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StormTideDailyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Surge_DATE', models.DateTimeField(default=datetime.datetime.now)),
                ('Tide_DATE', models.DateTimeField(default=datetime.datetime.now)),
                ('nowdate', models.DateField(default=datetime.datetime.now)),
                ('Surge_VALUE', models.FloatField(default=999.0)),
                ('TideS_VALUE', models.FloatField(default=999.0)),
                ('CODE', models.CharField(default='ERROR', max_length=6)),
            ],
            options={
                'verbose_name': '每日预报风暴潮及增水极值及时间',
                'verbose_name_plural': '每日预报风暴潮及增水极值及时间',
            },
        ),
    ]
