# Generated by Django 2.0.4 on 2018-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StormTide', '0002_stormtidedailyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stormtidedailyinfo',
            old_name='TideS_VALUE',
            new_name='Tide_VALUE',
        ),
    ]
