# Generated by Django 2.0.4 on 2018-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='网格名称')),
                ('code', models.CharField(max_length=5, verbose_name='网格编码')),
                ('area', models.CharField(choices=[('n', '北海'), ('e', '东海'), ('s', '南海')], max_length=2, verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '网格信息',
                'verbose_name_plural': '网格信息',
            },
        ),

    ]
