# Generated by Django 2.0.4 on 2018-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50, verbose_name='海洋站名称')),
                ('code', models.CharField(max_length=6, verbose_name='海洋站站代码')),
                ('area', models.CharField(choices=[('n', '北海'), ('e', '东海'), ('s', '南海')], max_length=2, verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '海洋站信息',
                'verbose_name_plural': '海洋站信息',
            },
        ),
    ]
