# Generated by Django 2.0.4 on 2018-08-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_stationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='Lat',
            field=models.FloatField(default=1, max_length=6, verbose_name='维度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='Lon',
            field=models.FloatField(default=1, max_length=6, verbose_name='经度'),
            preserve_default=False,
        ),
    ]
