# Generated by Django 2.0.4 on 2018-08-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0003_auto_20180801_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinfo',
            name='remark',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='remark',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
    ]
